# fly.toml app configuration file generated for takashi-photos on 2023-07-21T21:49:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "takashi-photos"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
